; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.61030.0 

	TITLE	C:\Source\reed-util\fpu-vs-sse\ctor-test.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?staticDataVWM@@3PAUVectorWithMaker@@A		; staticDataVWM
_DATA	SEGMENT
?staticDataVWM@@3PAUVectorWithMaker@@A DD 03f800000r ; 1 ; staticDataVWM
	DD	040000000r			; 2
	DD	040400000r			; 3
	DD	040800000r			; 4
	DD	040a00000r			; 5
	DD	040c00000r			; 6
	DD	040e00000r			; 7
	DD	041000000r			; 8
	DD	041100000r			; 9
_DATA	ENDS
PUBLIC	??0VectorWithCtor@@QAE@MMM@Z			; VectorWithCtor::VectorWithCtor
PUBLIC	?aFunction@@YAXXZ				; aFunction
PUBLIC	?staticDataVWC@@3PAUVectorWithCtor@@A		; staticDataVWC
EXTRN	?forceToMemory@@YAXPBX@Z:PROC			; forceToMemory
EXTRN	__fltused:DWORD
;	COMDAT ?vwc@?1??aFunction@@YAXXZ@4UVectorWithCtor@@A
_BSS	SEGMENT
?vwc@?1??aFunction@@YAXXZ@4UVectorWithCtor@@A DB 0cH DUP (?) ; `aFunction'::`2'::vwc
_BSS	ENDS
;	COMDAT ?$S1@?1??aFunction@@YAXXZ@4IA
_BSS	SEGMENT
?$S1@?1??aFunction@@YAXXZ@4IA DD 01H DUP (?)		; `aFunction'::`2'::$S1
_BSS	ENDS
_DATA	SEGMENT
?staticDataVWC@@3PAUVectorWithCtor@@A DD 03f800000r ; 1	; staticDataVWC
	DD	040000000r			; 2
	DD	040400000r			; 3
	DD	040800000r			; 4
	DD	040a00000r			; 5
	DD	040c00000r			; 6
	DD	040e00000r			; 7
	DD	041000000r			; 8
	DD	041100000r			; 9
_DATA	ENDS
;	COMDAT ?vwm@?1??aFunction@@YAXXZ@4UVectorWithMaker@@A
_DATA	SEGMENT
?vwm@?1??aFunction@@YAXXZ@4UVectorWithMaker@@A DD 03f800000r ; 1 ; `aFunction'::`2'::vwm
	DD	040000000r			; 2
	DD	040400000r			; 3
_DATA	ENDS
; Function compile flags: /Ogtp
; File c:\source\reed-util\fpu-vs-sse\ctor-test.cpp
;	COMDAT ?aFunction@@YAXXZ
_TEXT	SEGMENT
?aFunction@@YAXXZ PROC					; aFunction, COMDAT

; 37   : 	static VectorWithMaker vwm = { 1, 2, 3 };
; 38   : 	static VectorWithCtor vwc(1, 2, 3);

	mov	eax, DWORD PTR ?$S1@?1??aFunction@@YAXXZ@4IA
	test	al, 1
	jne	SHORT $LN5@aFunction
	or	eax, 1
	mov	DWORD PTR ?$S1@?1??aFunction@@YAXXZ@4IA, eax

; 23   : 		data[0] = x; data[1] = y; data[2] = z;

	mov	DWORD PTR ?vwc@?1??aFunction@@YAXXZ@4UVectorWithCtor@@A, 1065353216 ; 3f800000H
	mov	DWORD PTR ?vwc@?1??aFunction@@YAXXZ@4UVectorWithCtor@@A+4, 1073741824 ; 40000000H
	mov	DWORD PTR ?vwc@?1??aFunction@@YAXXZ@4UVectorWithCtor@@A+8, 1077936128 ; 40400000H
$LN5@aFunction:

; 39   : 
; 40   : 	forceToMemory(&vwm);

	push	OFFSET ?vwm@?1??aFunction@@YAXXZ@4UVectorWithMaker@@A
	call	?forceToMemory@@YAXPBX@Z		; forceToMemory

; 41   : 	forceToMemory(&vwc);

	push	OFFSET ?vwc@?1??aFunction@@YAXXZ@4UVectorWithCtor@@A
	call	?forceToMemory@@YAXPBX@Z		; forceToMemory
	add	esp, 8

; 42   : }

	ret	0
?aFunction@@YAXXZ ENDP					; aFunction
_TEXT	ENDS
; Function compile flags: /Ogtp
; File c:\source\reed-util\fpu-vs-sse\ctor-test.cpp
;	COMDAT ??0VectorWithCtor@@QAE@MMM@Z
_TEXT	SEGMENT
_x$ = 8							; size = 4
_y$ = 12						; size = 4
_z$ = 16						; size = 4
??0VectorWithCtor@@QAE@MMM@Z PROC			; VectorWithCtor::VectorWithCtor, COMDAT
; _this$ = ecx

; 21   : 	VectorWithCtor(float x, float y, float z)

	push	ebp
	mov	ebp, esp

; 22   : 	{
; 23   : 		data[0] = x; data[1] = y; data[2] = z;

	movss	xmm0, DWORD PTR _x$[ebp]
	movss	DWORD PTR [ecx], xmm0
	movss	xmm0, DWORD PTR _y$[ebp]
	movss	DWORD PTR [ecx+4], xmm0
	movss	xmm0, DWORD PTR _z$[ebp]
	movss	DWORD PTR [ecx+8], xmm0

; 24   : 	}

	mov	eax, ecx
	pop	ebp
	ret	12					; 0000000cH
??0VectorWithCtor@@QAE@MMM@Z ENDP			; VectorWithCtor::VectorWithCtor
_TEXT	ENDS
END
