; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.61030.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?staticDataVWM@@3PAUVectorWithMaker@@A		; staticDataVWM
_DATA	SEGMENT
?staticDataVWM@@3PAUVectorWithMaker@@A DD 03f800000r ; 1 ; staticDataVWM
	DD	040000000r			; 2
	DD	040400000r			; 3
	DD	040800000r			; 4
	DD	040a00000r			; 5
	DD	040c00000r			; 6
	DD	040e00000r			; 7
	DD	041000000r			; 8
	DD	041100000r			; 9
_DATA	ENDS
PUBLIC	??0VectorWithCtor@@QEAA@MMM@Z			; VectorWithCtor::VectorWithCtor
PUBLIC	?aFunction@@YAXXZ				; aFunction
PUBLIC	?staticDataVWC@@3PAUVectorWithCtor@@A		; staticDataVWC
PUBLIC	__real@3f800000
PUBLIC	__real@40000000
PUBLIC	__real@40400000
EXTRN	?forceToMemory@@YAXPEBX@Z:PROC			; forceToMemory
EXTRN	_fltused:DWORD
;	COMDAT ?vwc@?1??aFunction@@YAXXZ@4UVectorWithCtor@@A
_BSS	SEGMENT
?vwc@?1??aFunction@@YAXXZ@4UVectorWithCtor@@A DB 0cH DUP (?) ; `aFunction'::`2'::vwc
_BSS	ENDS
;	COMDAT ?$S1@?1??aFunction@@YAXXZ@4IA
_BSS	SEGMENT
?$S1@?1??aFunction@@YAXXZ@4IA DD 01H DUP (?)		; `aFunction'::`2'::$S1
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?aFunction@@YAXXZ DD imagerel $LN8
	DD	imagerel $LN8+99
	DD	imagerel $unwind$?aFunction@@YAXXZ
pdata	ENDS
;	COMDAT __real@40400000
CONST	SEGMENT
__real@40400000 DD 040400000r			; 3
CONST	ENDS
;	COMDAT __real@40000000
CONST	SEGMENT
__real@40000000 DD 040000000r			; 2
CONST	ENDS
;	COMDAT __real@3f800000
CONST	SEGMENT
__real@3f800000 DD 03f800000r			; 1
CONST	ENDS
_DATA	SEGMENT
	ORG $+4
?staticDataVWC@@3PAUVectorWithCtor@@A DD 03f800000r ; 1	; staticDataVWC
	DD	040000000r			; 2
	DD	040400000r			; 3
	DD	040800000r			; 4
	DD	040a00000r			; 5
	DD	040c00000r			; 6
	DD	040e00000r			; 7
	DD	041000000r			; 8
	DD	041100000r			; 9
_DATA	ENDS
;	COMDAT ?vwm@?1??aFunction@@YAXXZ@4UVectorWithMaker@@A
_DATA	SEGMENT
?vwm@?1??aFunction@@YAXXZ@4UVectorWithMaker@@A DD 03f800000r ; 1 ; `aFunction'::`2'::vwm
	DD	040000000r			; 2
	DD	040400000r			; 3
_DATA	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?aFunction@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Ogtpy
; File c:\source\reed-util\fpu-vs-sse\ctor-test.cpp
;	COMDAT ?aFunction@@YAXXZ
_TEXT	SEGMENT
?aFunction@@YAXXZ PROC					; aFunction, COMDAT

; 36   : {

$LN8:
	sub	rsp, 40					; 00000028H

; 37   : 	static VectorWithMaker vwm = { 1, 2, 3 };
; 38   : 	static VectorWithCtor vwc(1, 2, 3);

	mov	eax, DWORD PTR ?$S1@?1??aFunction@@YAXXZ@4IA
	test	al, 1
	jne	SHORT $LN5@aFunction

; 23   : 		data[0] = x; data[1] = y; data[2] = z;

	movss	xmm0, DWORD PTR __real@3f800000
	movss	xmm1, DWORD PTR __real@40000000

; 37   : 	static VectorWithMaker vwm = { 1, 2, 3 };
; 38   : 	static VectorWithCtor vwc(1, 2, 3);

	or	eax, 1
	mov	DWORD PTR ?$S1@?1??aFunction@@YAXXZ@4IA, eax

; 23   : 		data[0] = x; data[1] = y; data[2] = z;

	movss	DWORD PTR ?vwc@?1??aFunction@@YAXXZ@4UVectorWithCtor@@A, xmm0
	movss	xmm0, DWORD PTR __real@40400000
	movss	DWORD PTR ?vwc@?1??aFunction@@YAXXZ@4UVectorWithCtor@@A+4, xmm1
	movss	DWORD PTR ?vwc@?1??aFunction@@YAXXZ@4UVectorWithCtor@@A+8, xmm0
$LN5@aFunction:

; 39   : 
; 40   : 	forceToMemory(&vwm);

	lea	rcx, OFFSET FLAT:?vwm@?1??aFunction@@YAXXZ@4UVectorWithMaker@@A
	call	?forceToMemory@@YAXPEBX@Z		; forceToMemory

; 41   : 	forceToMemory(&vwc);

	lea	rcx, OFFSET FLAT:?vwc@?1??aFunction@@YAXXZ@4UVectorWithCtor@@A

; 42   : }

	add	rsp, 40					; 00000028H

; 41   : 	forceToMemory(&vwc);

	jmp	?forceToMemory@@YAXPEBX@Z		; forceToMemory
?aFunction@@YAXXZ ENDP					; aFunction
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File c:\source\reed-util\fpu-vs-sse\ctor-test.cpp
;	COMDAT ??0VectorWithCtor@@QEAA@MMM@Z
_TEXT	SEGMENT
this$ = 8
x$ = 16
y$ = 24
z$ = 32
??0VectorWithCtor@@QEAA@MMM@Z PROC			; VectorWithCtor::VectorWithCtor, COMDAT

; 22   : 	{
; 23   : 		data[0] = x; data[1] = y; data[2] = z;

	movss	DWORD PTR [rcx], xmm1
	movss	DWORD PTR [rcx+4], xmm2
	movss	DWORD PTR [rcx+8], xmm3

; 24   : 	}

	mov	rax, rcx
	ret	0
??0VectorWithCtor@@QEAA@MMM@Z ENDP			; VectorWithCtor::VectorWithCtor
_TEXT	ENDS
END
